### ISSUE TITLE
Geofence node is located under input, not location

### ISSUE THREAD

**Issue by SamPant** [hardillb/node-red-node-geofence#10]
i installed geofence node using the "manage palette' option on node red, and this command : npm i node-red-node-geofence, but everytime the geofence node appears under input palette, not location. When i double-click the node to configure it, i can't choose the action ( points inside/outside or inarea property), because the action option is not showing. The only option i can configure is name, and there is also the option "add geofence manager". I also tried to install the geolib libarary using this command : npm install geolib, but i got the same results... any idea how to properly install geofence node? thanks in advance

**Comment by hardillb** [comment]
You just install the node-red-node-geofence node, nothing else.

There is no need to install geolib separately it will be pulled in by the node when it's installed.

If it's not working properly then you need to supply a LOT more information for me to be able to help.

- Version of Node-RED you are using
- Version of NodeJS you are using?
- Type and version of browser?
- Are there any errors in the Node-RED log?
- Are there any errors in the browser console?
- Where are you running Node-RED, locally or on a platform like IBMCloud?

**Comment by vd062** [comment]
Same issue here. There is no "Action" setting below the map. probably that's why it is returning false results. 
Node red version : 0.19.5. 
Node.js version 8.12.0. 
Browser : Chrome
No errors. Just returning false even if i am inside the geofence.
Running Node Red locally in Windows 10

![image](https://user-images.githubusercontent.com/46595618/51390994-e71bb180-1b56-11e9-8235-684a78f1c260.png)
![image](https://user-images.githubusercontent.com/46595618/51391040-04508000-1b57-11e9-8c5d-0c9e91573887.png)


From these Pictures, You can Have Idea about what's wrong...
at the bottom there is no "Action" drop down menu.  

And I was using Node-red-contrib-geofence

then I uninstalled it and downloaded Node-red-node-geofence and It seemd like there was no configuration node included with it. 

which method(palette) is preferable to get proper functioning?

**Comment by hardillb** [comment]
OK, I'll have a look this evening

**Comment by hardillb** [comment]
Quick question exactly which version of the node are you using. There are 2 on flows.nodered.org

The correct one is node-red-node-geofence at version 0.1.0 and this looks to be working just fine.

node-red-contrib-geofence at version 0.2.4 not this node, and maintained by somebody else.

**Comment by vd062** [comment]
Quick Answer - You Are Right! Thank you. contrib version had disturbed everything. So I uninstalled node-red and installed again and got node-geofence version 0.1.0. And now everything started working absolutely fine! Close the Question...
