### ISSUE TITLE
After new Nodered Update not working!

### ISSUE THREAD

**Issue by sp3cialck** [hardillb/node-red-node-geofence#30]
After the last nodered update (Current version: 12.0.2) the node ( node-red-node-geofence ) was by nodered uninstalled, and after trying to install it again i'm having this error:

2022-06-09T01:00:06.624Z Install : node-red-node-geofence 0.3.3

2022-06-09T01:00:06.519Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production --engine-strict node-red-node-geofence@0.3.3
2022-06-09T01:00:06.834Z [err] npm
2022-06-09T01:00:06.834Z [err]  WARN config production Use `--omit=dev` instead.
2022-06-09T01:00:07.822Z [err] npm
2022-06-09T01:00:07.822Z [err]  
2022-06-09T01:00:07.822Z [err] ERR! code ETARGET
2022-06-09T01:00:07.824Z [err] npm 
2022-06-09T01:00:07.825Z [err] ERR! notarget
2022-06-09T01:00:07.825Z [err]  No matching version found for geolib@^2.0.26.
2022-06-09T01:00:07.825Z [err] npm ERR!
2022-06-09T01:00:07.825Z [err]  
2022-06-09T01:00:07.825Z [err] notarget In most cases you or one of your dependencies are requesting
2022-06-09T01:00:07.825Z [err] npm
2022-06-09T01:00:07.825Z [err]  ERR! notarget a package version that doesn't exist.
2022-06-09T01:00:07.827Z [err] 
2022-06-09T01:00:07.827Z [err] npm 
2022-06-09T01:00:07.827Z [err] ERR! A complete log of this run can be found in:
2022-06-09T01:00:07.827Z [err] npm ERR!     /root/.npm/_logs/2022-06-09T01_00_06_805Z-debug-0.log
2022-06-09T01:00:07.833Z rc=1
```

**Comment by hitnrun30** [comment]
Just came here for this.  I looked through the updates for Node red.  I was also using looptimer and stoptimer and those were removed.  Those were easy to fix, but this wont allow for a reinstall.

**Comment by amurr81** [comment]
I am also having the same issue.

**Comment by hardillb** [comment]
First 12.0.2 is **NOT** a Node-RED version (It's some BS Home Assistant version number that is meaningless compared to the latest Node-RED release which is 2.2.2)

Also the latest geolib dependency in the package.json is 2.0.24 not 2.0.26 so that error doesn't make any sense....

So the question is what have Home Assistant changed, and why?

I don't use Home Assistant at all so until one of you can tell me, what the actual Node-RED, NodeJS, npm version is being used in all this I can't help, and I suggest you go ask the Home Assistant maintainers what they broke and if they tested any of this before releasing it.

**Comment by hardillb** [comment]
p.s. the latest version of the node-red-node-geofence node is 0.3.4 not 0.3.3

**Comment by frenck** [comment]
> It's some BS Home Assistant version number

👋  Hi follow open source maintainer, before shouting BS and things like that... it might help understand the reasoning behind it. Anyways...

Looking at npmjs, it seems like 0.3.4 was just published a couple of hours ago.

![CleanShot 2022-06-09 at 14 42 13](https://user-images.githubusercontent.com/195327/172849562-8341fff4-fee3-4ee4-a2b9-19052fc8d84f.png)

I cannot find a reference here on GitHub of those version numbers (and thus cannot see what has changed on this end). Could you point me to the commits that are included in the versions published?

Meanwhile, I will dive into the HA add-on end to figure out what could go wrong there. 👍 

../Frenck

**Comment by hitnrun30** [comment]
> > It's some BS Home Assistant version number
> 
> 👋 Hi follow open source maintainer, before shouting BS and things like that... it might help understand the reasoning behind it. Anyways...
> 
> Looking at npmjs, it seems like 0.3.4 was just published a couple of hours ago.
> 
> ![CleanShot 2022-06-09 at 14 42 13](https://user-images.githubusercontent.com/195327/172849562-8341fff4-fee3-4ee4-a2b9-19052fc8d84f.png)
> 
> I cannot find a reference here on GitHub of those version numbers (and thus cannot see what has changed on this end). Could you point me to the commits that are included in the versions published?
> 
> Meanwhile, I will dive into the HA add-on end to figure out what could go wrong there. 👍
> 
> ../Frenck

Always on top of things

**Comment by hardillb** [comment]
Apologies, I am the wrong end of a Red Eye from the US yesterday. It appears @dceejay messed up a publish yesterday and has not mentioned or pushed any of his updates to git before publishing to npm.

I stand by my HA Version BS comment though, we keep getting HA users raising core Node-RED issues stating it as their Node-RED version and it is truly meaningless to the NR community.  You need to make the REAL NR Version much more prominent (along with NodeJS and npm versions) in the environment so that if/when HA users raise Node-RED issues they can supply meaningful information.

The solution is to install 0.3.4

**Comment by frenck** [comment]
> it is truly meaningless to the NR community

Sorry to hear that. Unfortunately, there is more in this world than just the Node-RED version number. The add-on contains many moving parts. Node-RED itself is just one of them (a prominent one, that I agree on).

Node-RED has hidden their version number in the menu, which is retained. If you think Node-RED should show their version number in the interface more promptly, I'd suggest to raise an feature request with them.

-- 

Anyways, but my question is unanswered, yet this issue is closed?

> Could you point me to the commits that are included in the versions published?

It seems there is now a disconnect between what is published and what is in this repository. That sounds odd. Should I file a new bug report for that?

**Comment by frenck** [comment]
Noticed #31 

Thanks for that 👍
